name: core-build
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    uses: azerothcore/reusable-workflows/.github/workflows/core_build_modules.yml@main
    with:
      module_repo: ${{ github.event.repository.name }}
      module_path: server-side/mod-bg-slaveryvalley
      module_data: https://github.com/Helias/mod-bg-slaveryvalley/releases/download/1.0/server-data.zip
